[workspace]
members = [
  "kon_players",
  "kon_portal",
  "kon_rs",
  ]

  [workspace.dependencies]
  reqwest = { version = "0.11", features = ["json"] }
  tokio = { version = "1", features = ["full"] }
