[workspace]
resolver = "2"
members = [
  "kon_players",
  "kon_rs",
  "standalone"
  ]

  [workspace.dependencies]
  reqwest = { version = "0.11", features = ["json"] }
  tokio = { version = "1", features = ["full"] }
