[package]
name = "kon_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
csv = "*"
clap = { version = "4.5.19", features = ["derive"] }