[package]
name = "kon_players"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.3"
csv = "1.2"
serde = { version = "*", features = ["derive"] } # from csv
log = "0.4"